#pragma once

#include <uhook.hpp>

using namespace UE3;

UE3_PROCESSINTERNAL_HOOK(UTGameMatchInProgressBeginState);
UE3_PROCESSINTERNAL_HOOK(ActorSetInitialState);
UE3_PROCESSINTERNAL_HOOK(TrPlayerControllerReceiveLocalizedMessage);
UE3_PROCESSINTERNAL_HOOK(TrPlayerControllerClientShowAccoladeText);
UE3_PROCESSINTERNAL_HOOK(TrPlayerControllerClientSetHUD);
UE3_PROCESSINTERNAL_HOOK(TrPawnClientUpdateHUDHealth);
UE3_PROCESSINTERNAL_HOOK(WeaponClientGivenTo);
UE3_PROCESSINTERNAL_HOOK(TrDevice_AutoFireSwitchToPostFireDevice);